file_format: "1"
id: lapka_wellum36
name: LapkaWellum36
type: shield
url: https://github.com/braindefender/wellum
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - lapka_wellum36_left
  - lapka_wellum36_right
  - lapka_wellum36_dongle
